-- AlterTable: adiciona ADM_ARTHUR_SABOYA ao enum Permissao
ALTER TABLE `usuarios` MODIFY COLUMN `permissao` ENUM('DEV','ADM','TEC','ARTHUR_SABOYA','ADM_ARTHUR_SABOYA','USR','PONTO_FOCAL','COORDENADOR','PORTARIA','DIRETOR') NOT NULL DEFAULT 'PORTARIA';
